import { getProjectDir, loadAppSettingsFromProject, loadAutosFromProject, safeNameFromString } from './projectFolder.js';

const JAVA_PACKAGE = 'org.firstinspires.ftc.teamcode.brainstemPilotAuto.opmodeAutos';
const TEAM_BASE_PACKAGE = 'org.firstinspires.ftc.teamcode.brainstemPilotAuto';
const OPMODE_DIR = 'opmodeAutos';
const PILOT_AUTO_BASE_FILENAME = 'PilotAutoBase.java';
const GENERATED_MARKER = 'AUTO-GENERATED by Brainstem Pilot UI';
const TEAM_BASE_MARKER = 'TEAM-OWNED — Brainstem Pilot UI creates this file once and will not overwrite it';

/** Hand-maintained Java files in opmodeAutos — never deleted by sync. */
const STATIC_JAVA_FILES = new Set([]);

export function variantNameToClassName(displayName) {
  const parts = (displayName ?? '')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  if (parts.length === 0) {
    return 'VariantAuto';
  }

  let merged = parts
    .map(part => {
      if (/^\d+$/.test(part)) return part;
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join('');

  // Java class names cannot start with a digit — prefix with '_' only when required.
  if (!/^[A-Za-z_]/.test(merged)) {
    merged = `_${merged}`;
  }
  if (!merged.endsWith('Auto')) {
    merged += 'Auto';
  }
  return merged;
}

function escapeJavaString(value) {
  return (value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function buildFtcOpmodeJavaContent(displayName) {
  const className = variantNameToClassName(displayName);
  const variantId = safeNameFromString(displayName);
  const escapedName = escapeJavaString(displayName);

  return `package ${JAVA_PACKAGE};

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import org.firstinspires.ftc.teamcode.brainstemPilotAuto.PilotAutoBase;

/**
 * ${GENERATED_MARKER} — do not edit manually.
 * Variant: ${displayName}
 */
@Autonomous(name = "${escapedName}", group = "Pilot")
public class ${className} extends PilotAutoBase {
    public ${className}() {
        super("${variantId}");
    }
}
`;
}

export function ftcOpmodeJavaFilename(displayName) {
  return `${variantNameToClassName(displayName)}.java`;
}

export function buildPilotAutoBaseJavaContent() {
  return `package ${TEAM_BASE_PACKAGE};

import com.acmerobotics.dashboard.telemetry.TelemetryPacket;
import com.acmerobotics.roadrunner.Pose2d;

import org.brainstemfirst.pilot.ftc.PilotOpMode;
import org.brainstemfirst.pilot.ftc.bezier.follower.BezierFollowerConfig;
import org.brainstemfirst.pilot.ftc.model.FieldConstants;
import org.brainstemfirst.pilot.ftc.bezier.follower.BezierDrivePath;

import com.acmerobotics.roadrunner.PoseVelocity2d;

import java.util.function.Consumer;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;


/**
 * ${TEAM_BASE_MARKER}.
 * Wire your robot, drive, and {@code PilotRegistry.addCommand} calls here.
 * Generated OpModes in {@code opmodeAutos/} extend this class.
 */
public abstract class PilotAutoBase extends PilotOpMode {
    protected PilotAutoBase(String autoId) {
        super(autoId);
        configureFollower();
    }

    /** Bézier follower gains. Read every loop — edit these values here. */
    private void configureFollower() {
        // Use velocity profile for smoother motion.
        BezierFollowerConfig.useVelocityProfile = true;
        BezierFollowerConfig.velKv = 0.014;
        BezierFollowerConfig.velKs = 0.03;
        BezierFollowerConfig.velKp = 0.05;

        // Set cruise velocity/profile decel while tuning. 
        BezierFollowerConfig.overrideCruiseVel = false;
        BezierFollowerConfig.cruiseVel = 30;
        BezierFollowerConfig.overrideProfileDecel = false;
        BezierFollowerConfig.profileDecel = 40;

        // Cross-track error gains.
        BezierFollowerConfig.crossTrackKp = 0.05;
        BezierFollowerConfig.correctivePower = 0.7;

        // Heading error gains.
        BezierFollowerConfig.headingkP = 0.05;
        BezierFollowerConfig.headingkF = 0.05;

        // Speed error gains (ONLY used if useVelocityProfile is false)
        BezierFollowerConfig.speedkP = 0.05;
        BezierFollowerConfig.speedkF = 0.05;
        BezierFollowerConfig.speedkD = 0.0;
    }

    @Override
    protected void setupRobot(FieldConstants.Alliance alliance, Pose2d startPose) {
        // Construct your robot and seed odometry to startPose.
    }

    @Override
    protected Supplier<Pose2d> pose() {
        throw new IllegalStateException("Bind pose() in PilotAutoBase, e.g. drive::getPose");
    }

    @Override
    protected Supplier<PoseVelocity2d> lastVelRobot() {
        throw new IllegalStateException("Bind lastVelRobot() in PilotAutoBase, e.g. drive::lastVelRobot");
    }

    @Override
    protected Consumer<PoseVelocity2d> setDrivePowers() {
        throw new IllegalStateException("Bind setDrivePowers() in PilotAutoBase, e.g. drive::setDrivePowers");
    }

    @Override
    protected DoubleSupplier maxAngVel() {
        throw new IllegalStateException("Bind maxAngVel() in PilotAutoBase, e.g. drive::maxAngVel");
    }

    @Override
    protected void registerCommands() {
        // Names must match the editor: PilotRegistry.addCommand("Subsystem", "Command", () -> action);
    }

    @Override
    protected boolean updateRobot(TelemetryPacket packet) {
        // Subsystem loop + localizer update. Return true to keep running.

        // Add telemetry for the BezierDrivePath status.
        BezierDrivePath.Status s = BezierDrivePath.status();
        telemetry.addData("target X", s.targetPoint.x);
        telemetry.addData("target Y", s.targetPoint.y);
        telemetry.addData("heading rad", s.targetHeadingRad);
        telemetry.addData("remaining", s.remainingLength);
        telemetry.update();

        return true;
    }
}
`;
}

async function fileExists(dir, filename) {
  try {
    await dir.getFileHandle(filename, { create: false });
    return true;
  } catch {
    return false;
  }
}

/** Create {@code PilotAutoBase.java} in the project root if it is missing. Never overwrites. */
export async function ensureFtcPilotAutoBase() {
  if (!(await isFtcProject())) return;
  const root = getProjectDir();
  if (!root) return;
  if (await fileExists(root, PILOT_AUTO_BASE_FILENAME)) return;

  const fh = await root.getFileHandle(PILOT_AUTO_BASE_FILENAME, { create: true });
  const writable = await fh.createWritable();
  await writable.write(buildPilotAutoBaseJavaContent());
  await writable.close();
}

/**
 * Does `displayName` collide with another Auto's generated OpMode class?
 *
 * Class names strip every non-alphanumeric character, so "Nine Ball (123)" and
 * "Nine Ball 123" have distinct file slugs but both become `NineBall123Auto` — one .java
 * file, one of the two Autos silently unreachable from the Driver Station. Slug uniqueness
 * is not enough; this is the check that matters for FTC.
 *
 * @param existingAutos every Auto in the project
 * @param currentId     the Auto being renamed, so it does not clash with itself
 * @returns the Auto it collides with, or null
 */
export function ftcClassNameClash(displayName, existingAutos, currentId) {
  const target = variantNameToClassName(displayName);
  return (existingAutos ?? []).find(a =>
    (a.id ?? a._id) !== currentId && variantNameToClassName(a.name) === target) ?? null;
}

async function isFtcProject() {
  const settings = await loadAppSettingsFromProject();
  return settings?.projectType === 'ftc';
}

async function getOpmodeAutosDir() {
  const root = getProjectDir();
  if (!root) return null;
  return root.getDirectoryHandle(OPMODE_DIR, { create: true });
}

async function writeOpmodeJavaFile(displayName) {
  const dir = await getOpmodeAutosDir();
  if (!dir || !displayName?.trim()) return;

  const filename = ftcOpmodeJavaFilename(displayName);
  const content = buildFtcOpmodeJavaContent(displayName.trim());
  const fh = await dir.getFileHandle(filename, { create: true });
  const writable = await fh.createWritable();
  await writable.write(content);
  await writable.close();
}

async function deleteOpmodeJavaFile(displayName) {
  const dir = await getOpmodeAutosDir();
  if (!dir || !displayName?.trim()) return;

  const filename = ftcOpmodeJavaFilename(displayName);
  try {
    await dir.removeEntry(filename);
  } catch {
    /* ignore missing file */
  }
}

async function isGeneratedOpmodeFile(dir, filename) {
  if (!filename.endsWith('.java') || STATIC_JAVA_FILES.has(filename)) {
    return false;
  }
  try {
    const fh = await dir.getFileHandle(filename);
    const text = await (await fh.getFile()).text();
    return text.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/** Create or update one FTC OpMode Java file for an Auto. */
export async function syncFtcOpmodeAuto(autoObj, previousName = null) {
  if (!(await isFtcProject())) return;
  if (!autoObj?.name?.trim()) return;

  await ensureFtcPilotAutoBase();

  if (previousName && previousName.trim() && previousName.trim() !== autoObj.name.trim()) {
    await deleteOpmodeJavaFile(previousName.trim());
  }

  await writeOpmodeJavaFile(autoObj.name.trim());
}

/** Remove the FTC OpMode Java file for a deleted Auto. */
export async function deleteFtcOpmodeAuto(displayName) {
  if (!(await isFtcProject())) return;
  if (!displayName?.trim()) return;
  await deleteOpmodeJavaFile(displayName.trim());
}

/**
 * Remove generated OpMode files from a project that is not FTC.
 *
 * `syncAllFtcOpmodeAutos` bails early when the project is not FTC, so a project that was ever
 * opened as FTC — or that had files copied in from an FTC project — kept orphaned Java under
 * `opmodeAutos/`. On FRC that folder sits inside `deploy/`, so the dead files get pushed to
 * the roboRIO. Only files carrying the generated marker are touched.
 */
export async function purgeFtcOpmodesWhenNotFtc() {
  if (await isFtcProject()) return;
  const root = getProjectDir();
  if (!root) return;

  let dir;
  try {
    dir = await root.getDirectoryHandle(OPMODE_DIR, { create: false });
  } catch {
    return; // nothing to clean
  }

  let remaining = 0;
  for await (const entry of dir.values()) {
    if (entry.kind === 'file' && await isGeneratedOpmodeFile(dir, entry.name)) {
      try { await dir.removeEntry(entry.name); continue; } catch { /* ignore */ }
    }
    remaining += 1;
  }
  if (remaining === 0) {
    try { await root.removeEntry(OPMODE_DIR, { recursive: true }); } catch { /* ignore */ }
  }
}

/** Regenerate all FTC OpMode files from autos/ and remove stale generated files. */
export async function syncAllFtcOpmodeAutos() {
  if (!(await isFtcProject())) return;

  await ensureFtcPilotAutoBase();

  const autos = (await loadAutosFromProject()) ?? [];
  const expectedFiles = new Set(
    autos
      .filter(a => a?.name?.trim())
      .map(a => ftcOpmodeJavaFilename(a.name.trim()))
  );

  for (const auto of autos) {
    if (auto?.name?.trim()) {
      await writeOpmodeJavaFile(auto.name.trim());
    }
  }

  const dir = await getOpmodeAutosDir();
  if (!dir) return;

  for await (const entry of dir.values()) {
    if (entry.kind !== 'file' || !entry.name.endsWith('.java')) continue;
    if (STATIC_JAVA_FILES.has(entry.name)) continue;
    if (expectedFiles.has(entry.name)) continue;
    if (await isGeneratedOpmodeFile(dir, entry.name)) {
      try {
        await dir.removeEntry(entry.name);
      } catch {
        /* ignore */
      }
    }
  }
}
